# frozen_string_literal: true
source "https://rubygems.org"
gem "fastlane", "~> 2.228"

plugins_path = File.join(File.dirname(__FILE__), 'android', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

plugins_path_ios = File.join(File.dirname(__FILE__), 'ios', 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path_ios) if File.exist?(plugins_path_ios)
