name: customer_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Dependency Injection
  get_it: ^8.2.0
  injectable: ^2.3.2

  # Core packages
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  network:
    path: ../../packages/network
  local_storage:
    path: ../../packages/local_storage
  localization:
    path: ../../packages/localization
  share:
    path: ../../packages/share

  # Feature packages
  features_auth:
    path: ../../packages/features/features_auth
  features_user:
    path: ../../packages/features/features_user
  features_home:
    path: ../../packages/features/features_home
  features_onboarding:
    path: ../../packages/features/features_onboarding
  features_splash:
    path: ../../packages/features/features_splash

  # Storage dependencies
  shared_preferences: ^2.5.3

  # Routing
  go_router: ^17.0.1

  # Utilities
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  equatable: ^2.0.7

  # force update
  upgrader: ^12.4.0

  # Firebase dependencies
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.0
  build_runner: ^2.9.0
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env.dev
    - .env.uat
    - .env.prod

# Melos 7.x
resolution: workspace